#!/usr/bin/env bash
# Pulls the latest common-config and regenerates ~/.claude/CLAUDE.md from
# the shared fragment + this device's fragment. Idempotent; safe to run at
# SessionStart. Silent on success when run with --quiet.

set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
quiet=0
device_id=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --quiet) quiet=1 ;;
        --device-id) device_id="$2"; shift ;;
        --device-id=*) device_id="${1#*=}" ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
    shift
done

host="${device_id:-${COMMON_CONFIG_DEVICE_ID:-$(hostname)}}"
host="$(echo "$host" | tr '[:upper:]' '[:lower:]')"

log() { [[ $quiet -eq 0 ]] && echo "$@"; }

# 1. Pull
if ! git -C "$repo" pull --ff-only --quiet 2>/dev/null; then
    [[ $quiet -eq 0 ]] && echo "common-config: pull failed (offline, conflict, or non-ff). Skipping." >&2
    # Don't exit — still recompose from local state below.
fi

# 2. Compose ~/.claude/CLAUDE.md
shared="$repo/claude-md/shared.md"
device="$repo/devices/$host/CLAUDE.md"
out="$HOME/.claude/CLAUDE.md"

if [[ ! -f "$shared" ]]; then
    echo "common-config: missing $shared" >&2
    exit 1
fi
if [[ ! -f "$device" ]]; then
    echo "common-config: missing $device — has this device been onboarded?" >&2
    exit 1
fi

mkdir -p "$(dirname "$out")"
{
    echo "<!-- generated by common-config/scripts/refresh.sh — do not edit by hand -->"
    echo
    cat "$shared"
    echo
    echo "---"
    echo
    cat "$device"
} > "$out"

log "common-config: refreshed ($host)"
