# Pulls the latest common-config and regenerates ~/.claude/CLAUDE.md from
# the shared fragment + this device's fragment. Idempotent; safe to run at
# SessionStart. Pass -Quiet to suppress success output.

param([switch]$Quiet, [string]$DeviceId)

$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

if ($DeviceId) {
    $host_ = $DeviceId.ToLower()
} elseif ($env:COMMON_CONFIG_DEVICE_ID) {
    $host_ = $env:COMMON_CONFIG_DEVICE_ID.ToLower()
} else {
    $host_ = ([System.Net.Dns]::GetHostName()).ToLower()
}

function Log($msg) { if (-not $Quiet) { Write-Host $msg } }

# 1. Pull (stderr left visible on real failures; --quiet suppresses normal chatter)
git -C $repo pull --ff-only --quiet
if ($LASTEXITCODE -ne 0 -and -not $Quiet) {
    Write-Warning "common-config: pull failed (offline, conflict, or non-ff). Skipping."
}
# Don't throw on pull failure — still recompose from local state below.

# 2. Compose ~/.claude/CLAUDE.md
$shared = Join-Path $repo 'claude-md\shared.md'
$device = Join-Path $repo "devices\$host_\CLAUDE.md"
$out    = Join-Path $HOME '.claude\CLAUDE.md'

if (-not (Test-Path $shared)) { throw "common-config: missing $shared" }
if (-not (Test-Path $device)) { throw "common-config: missing $device - has this device been onboarded?" }

New-Item -ItemType Directory -Force (Split-Path $out) | Out-Null

$content = @(
    '<!-- generated by common-config/scripts/refresh.ps1 - do not edit by hand -->'
    ''
    (Get-Content $shared -Raw -Encoding utf8)
    ''
    '---'
    ''
    (Get-Content $device -Raw -Encoding utf8)
) -join "`n"

# Write UTF-8 *without* BOM (PS 5.1 'utf8' includes a BOM; use raw .NET to skip it).
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($out, $content, $utf8NoBom)

# 3. Reconcile skill symlinks — create symlinks for any repo skill that doesn't
#    yet have one in ~/.claude/skills/. Conservative: never replaces or removes
#    existing entries (that's the onboarder's job).
$skillsRepo = Join-Path $repo 'skills'
$skillsLive = Join-Path $HOME '.claude\skills'
if (Test-Path $skillsRepo) {
    New-Item -ItemType Directory -Force $skillsLive | Out-Null
    foreach ($d in Get-ChildItem $skillsRepo -Directory) {
        $link = Join-Path $skillsLive $d.Name
        $exists = $null -ne (Get-Item -LiteralPath $link -Force -ErrorAction SilentlyContinue)
        if (-not $exists) {
            try {
                New-Item -ItemType SymbolicLink -Path $link -Target $d.FullName -ErrorAction Stop | Out-Null
                Log "common-config: linked skill $($d.Name)"
            } catch {
                if (-not $Quiet) { Write-Warning "common-config: failed to link skill $($d.Name) - $_" }
            }
        }
    }
}

Log "common-config: refreshed ($host_)"
